### ISSUE TITLE
LAPACK library, default to read numpy default?

### ISSUE THREAD

**Issue by zerothi** [atztogo/phono3py#1]
If one wishes to use other libraries than the standard lapack interface it requires an editing in the `setup.py` file.

Instead one may use `numpy.distutils` to retrieve the fields specified in the numpy installation for a correct library.

For instance:
```
import numpy.distutils.system_info as si
lapack_opt_dict = si.get_info('lapack_opt')
```
will return the specified options in the `site.cfg` of the numpy installation. There are various things to query in the dictionary, such as library names, compilation flags, etc.

**Comment by atztogo** [comment]
This is new to me. Thanks for letting me know this. What is specially needed by phono3py is Lapacke. For Lapack and BLAS, your suggestion seems to work, but I think it may not do for lapacke, though if openblas is used, probably lapacke is in it, so it can work. Am I correct?

**Comment by zerothi** [comment]
Yes, you are correct. However, one can "test" using the distutils for the lapacke interface and then add that to the linker line, if needed. It was just a suggestion :)

**Comment by atztogo** [comment]
I will remember this information. Thanks.

**Comment by atztogo** [comment]
I will close this issue.

**Comment by zerothi** [comment]
Hi, I still have this issue. You have created your own scripting around this problem, but it does not handle all corner cases. You could get by without lots of these work-arounds by fetching the numpy lapack/blas equivalents. Currently I cannot build phono3py against blis without changing the build-system.

**Comment by atztogo** [comment]
I've never tested BLIS. Do you have any idea how to make it work?

**Comment by zerothi** [comment]
It should just be a matter of linking `-lblis` instead of `-lopenblas`, however, I would much prefer a cleaner solution that relies on the `numpy` wrappers.

Or, if you have generic user-defined work-arounds that does not require editing your `setup.py`.

**Comment by atztogo** [comment]
It would be nice to have the feature that you suggest, but it is difficult for me to work for it right now because I have other works being stacked. If you are interested in implementing it, i would appreciate your PR.
