### ISSUE TITLE
How to calculate three-phonon scattering phasespace in Phono3py ?

### ISSUE THREAD

**Issue by weileiweilei** [atztogo/phono3py#17]
Dear Professor Togo:
I noticed that JDOS can be obtained on a specific q-points. How could I obtain JDOS throughout the whole Brillouin zone, is there any command options of phono3py to help me realizing this conveniently? 
Best wishes !

Lei Wei

**Comment by atztogo** [comment]
There is no command line interface for exactly what you might expect. Though not straightforward, but you can get the value using ``--jdos`` option at the phonon frequency.
https://atztogo.github.io/phono3py/command-options.html#jdos-joint-density-of-states
The best way is probably using API, but you need some skill on python.

**Comment by weileiweilei** [comment]
Dear Professor Togo:
In your paper titled "Distributions of phonon lifetimes in Brillouin zones" ,w-JDOS (N2) of ZnTe as functions of wave vector between Γ-L and phonon frequency are obtained in Fig. 7. How did it realize ?
Thank you very much !

**Comment by atztogo** [comment]
I used ``--jdos`` at q-points along Gamma-L to get the data. Then I wrote a script to draw the plot.

**Comment by weileiweilei** [comment]
Thank you !
