### ISSUE TITLE
Importing fc3 using the Python API

### ISSUE THREAD

**Issue by mesonepigreco** [atztogo/phono3py#18]
Dear developers,
I have already obtained second and third order force constants by using another numerical tool. I would like to import them in phono3py to compute self-energy and the phonon lifetimes, however, indeed, they are in a file-format that does not match the phono3py. 
I would like to write a conversion script.
As far as I understood, phono3py is able to load the third order force constant matrix in several data types, but I have not found a specific documentation on how they should be written. 
In particular, I loaded the fc3 in python numpy array (shape = (3*nat_sc, 3*nat_sc, 3*nat_sc), nat_sc = number of atoms in the supercell), and similarly the fc2 
I tried to look a bit into the code and saw the function  "write_fc3_to_hdf5" (file_IO.py) but in the docstring it says it requires a numpy array of shape: (n_satom,n_satom,3,3). This seems to me a 2-rank tensor.

How can I convert my python 2rank and 3rank tensors into a file that can be read by phono3py?
What unit is used for the force constant matrices in phono3py?

Thank you for the attention!
Bests

**Comment by atztogo** [comment]
You may find the file format at https://atztogo.github.io/phono3py/output-files.html#fc3-hdf5 .
The physical unit of fc2 and fc3 are eV/A^2 and ev/A^3, respectively https://atztogo.github.io/phono3py/interfaces.html#physical-unit . If it's unclear, please ask.

Yes, I see, the docstring of write_fc3_to_hdf5 tells wrong about the format (I fixed it in the local repository, thanks!). `p2s_map` is optional when using compact format of `(n_patom,n_satom,n_satom,3,3)`. When using compact form and `p2s_map` is given, the indices of the atoms in primitive cell are checked if they are aligned in the correct order of phono3py (can be obtained by `phono3py.primitive.p2s_map` from API). But if you don't care about file (data) size, I recommend using the full format `(n_satom,n_satom,n_satom,3,3,3)` in which case you don't need to set `p2s_map`.

**Comment by mesonepigreco** [comment]
Thank you a lot for the information. I missed the two paragraph you linked from the documentation. 
I will try to see if I success.
Thank you a lot,
Bests!
