### ISSUE TITLE
can not obtain the fc3 in the phono3py

### ISSUE THREAD

**Issue by JustusLiang** [atztogo/phono3py#20]
Dear Professor Togo,
When I obtain fc3, I find that there is an error "Number of files to be read don't match to number of displacements in disp_fc3.yaml". But when I count the number of vasprun.xml , I find it can be matched. How can I solve this problem?

Sincerely
Justus liang

**Comment by atztogo** [comment]
Please send your question to the phonopy mailing list.

**Comment by JustusLiang** [comment]
Thank you very much!
