### ISSUE TITLE
Identical displacements in displacement dataset

### ISSUE THREAD

**Issue by tpurcell90** [atztogo/phono3py#22]
Dear Togo,

I was using phono3py to calculate third order force constants of a set of orthorhombic materials using and noticed that some of the displacements in the dataset were the same (I attached a sample POSCAR of the primitive cell).

Using a 1x1x1 supercell (the issue also appears in larger cells) displacements (syntax [first_atoms_index, second_atoms_index]) [2, 3], [3,3], [4,2] all correspond to moving along the +/- disp along y or z axis for displacement and then moving it -/+ disp along the same axis for displacement 2.
There are also a series of displacements where displacement 1 and displacement 2 are swapped with each other.

This should not affect the force constant calculations, but it does add a bit of computational load.

[POSCAR.txt](https://github.com/atztogo/phono3py/files/3176339/POSCAR.txt)

**Comment by atztogo** [comment]
I know it. I think the force constants calculation will be done by external software, such as ALM (https://alamode.readthedocs.io/en/latest/alm_root.html) or hiPhive (https://hiphive.materialsmodeling.org/). So I consider it is unnecessary to put my effort for this part of phono3py. But I should provide convenient interfaces to those force constants calculator, which is under consideration. How do you think?

**Comment by tpurcell90** [comment]
Okay that would work. If you are going to change how you calculate the force constant calculations then fixing this would not be worth it.

I'll close this issue.

**Comment by atztogo** [comment]
It may be useful for users to know the existence of duplicates when unit cell is large. I made a branch remove-duplicate-disps. By this you can get 'disp_fc3.yaml' with duplicates information like.

```
duplicates:
- 631 : 223
```

This means displacement of displacement id 631 is the same as that of id 223. This id in `disp_fc3.yaml` is counted including those for single displacement starting with index 1. If you use it from API, it counts from index 0 only for pair displacements. I haven't test this carefully yet.
