### ISSUE TITLE
Scattering rate between two phonon modes. 

### ISSUE THREAD

**Issue by fbcrs** [atztogo/phono3py#23]
Dear Prof. Togo, 

I have recently started to explore some of the features of phono3py, but I admit that I am still a relatively new user. I am trying to compute the scattering rate (integrated over all momenta) between two phonons using phono3py, namely, the rate at which a phonon \nu_1 is excited by the decay of a phonon \nu_2 and viceversa. 

If my understanding of the theory is correct, this scattering rate should be closely related to the \Omega'  (or equivalently \Omega) quantity defined right below Eq. (2) in Chaput, Phys. Rev. Lett. (2013) https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.110.265506 . 
However, the collision matrix printed out by phono3py in the file collision-m111111.hdf5 seems to be rather the \tilde\Omega quantity defined at the bottom of the right column of page 2 of Chaput's paper  (based on what I can deduce from the number of indices).

The transformation that yields \tilde\Omega from \Omega' involves some symmetry operation which acts only on momentum space. Therefore, my question is whether it is legitimate to interpret the matrix \tilde\Omega stored in collision-m111111.hdf5 as a two-phonon scattering rate. 

Thank you in advance for you help. 

Sincerely, 
Fabio Caruso

(Humboldt University Berlin, Germany)

**Comment by atztogo** [comment]
If I remember correctly, what you wrote at the last part is not easy.
