### ISSUE TITLE
kaccum error

### ISSUE THREAD

**Issue by Movaffaq** [atztogo/phono3py#27]
Dear Togo
I have installed the recent phono3py update according to new instructions. But I received the following error when calling kaccum (or phono3py-kaccum):

Traceback (most recent call last):
  File "~/miniconda/envs/phono3py/bin/phono3py-kaccum", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "~/run/phono3py/scripts/phono3py-kaccum", line 7, in <module>
    from phonopy.interface import read_crystal_structure
ImportError: cannot import name 'read_crystal_structure' from 'phonopy.interface' (~/run/phonopy/phonopy/interface/__init__.py)

I am completely unfamiliar with conda installation but does this conda installation requires setting $PYTHONPATH? I have noticed it does not copy anything to ~/miniconda/envs/phono3py/lib/python3.7/site-packages just an egg.info referring to ~/run/phonopy/phonopy 

Any help would be highly appreciated since I completely removed my older version ;).

Kind regards,
MK

**Comment by atztogo** [comment]
Thanks. This is a bug that kaccum didn't follow the recent update of phonopy. I fixed it, see https://github.com/atztogo/phono3py/commit/39a91213c1c5c8103a851a9972edbd58c5dc69a2.

This fix is already in master branch and released soon.

**Comment by atztogo** [comment]
I will close this issue.
