### ISSUE TITLE
How to test --sigma and --sigma-cutoff

### ISSUE THREAD

**Issue by xiangpan2017** [atztogo/phono3py#28]
Dear Prof. Atztogo,

If I want to use the smearing method for BZ integration, how should I test --sigma and --sigma-cutoff parameters? I tried --sigma=0.1 0.001 0.00001 and --sigma-cutoff=0 20 50 80 (0 means no --sigma-cutoff) to calculate the lattice thermal conductivity of  graphene. However, the results are very different from the published paper. So, do you have some suggestions for testing these two parameters?

Thank you very much!

Best,
Pan

**Comment by atztogo** [comment]
Could you send this post to the phonopy mailing list? Please indicate how different from published paper should be clearly mentioned. In addition, you probably don't understand the value of sigma-cutoff means. I close this issue.

**Comment by xiangpan2017** [comment]
Thank you for your reply! I have subscribed to the "Phonopy-users" mailing list and then send mail to phonopy-users@lists.sourceforge.net.
