### ISSUE TITLE
the  frequency  range of  JDOS question 

### ISSUE THREAD

**Issue by jialinji** [atztogo/phono3py#29]
Dear Togo,
when I use phono3py to plot jdos,I found  the code is f_max = np.max(self._frequencies) * 2.
 I'm confused why frequency_max multiply by 2 .
Thank you very much!

**Comment by atztogo** [comment]
I see you confused. But what do you want me to explain?

**Comment by jialinji** [comment]
Dear Togo,
The phonon frequency is cutoff at maximum frequency. What is physical meaning in the range of [frequency_max , frequency_max*2]. 
Thanks!

**Comment by atztogo** [comment]
Because it's three phonon process. Please send this kind of question to the phonopy mailing from next time.

**Comment by jialinji** [comment]
Suddenly realized.Thank you very much!
