### ISSUE TITLE
--write-gamma do not work with the direct solution of LBTE

### ISSUE THREAD

**Issue by panxiang2019** [atztogo/phono3py#31]
Dear Prof. Atztogo,

I installed the latest phono3py (version: 1.18.2) to calculate thermal conductivity. Unfortunately, the --write-gamma option do not generate the kappa-mxxx-gx.hdf5 file in case of using the direct solution of LBTE (--lbte option). Do you have any idea? 

BTW, if use the RTA method (--br option), it generates the kappa-mxxx-gx.hdf5 file normally.

Best,
Pan

**Comment by atztogo** [comment]
If you need only gamma, you can run with `--br`. If you need to run `--lbte`, you can use `--write-collision` option instead of `--write-gamma`.

**Comment by panxiang2019** [comment]
Dear Prof. Atztogo,

I find that using --write-collision option will generate many large collision-m80801-gx-s0.01.hdf5 files. Does Phono3py have a function to merge them into a collision-m80801-s0.01.hdf5 file?

Best,
Pan

**Comment by atztogo** [comment]
Please read the documentation. If you can't find any solution even after the documentation, please send your question to the phonopy mailing list but not here.
