### ISSUE TITLE
Question about Phono3py

### ISSUE THREAD

**Issue by weiyidan** [atztogo/phono3py#33]
Dear professor,

Thanks for developing phono3py for science research. As a freshman, i have some questions. In order to avoid disturbing you much time, let me give a brief description.

Firstly, what is the difference between group velocity and gv_by_gv in hdf5 file? I notice they are not the same.

Secondly, how can i get group velocity from phono3py? I tried to use "phono3py-kaccum --pa="0 1/2 1/2 1/2 0 1/2 1/2 1/2 0" -c POSCAR-unitcell kappa-m111111.hdf5 --gv --average |tee kaccum.dat". Is it possible to adjust the X-axis range? 

Thanks for showing some lights for me. ^.^

Bests,

**Comment by atztogo** [comment]
Please send your questions to the phonopy mailing list. I will close this issue.
