### ISSUE TITLE
calculation of gruneisen parameters seems to  be broken

### ISSUE THREAD

**Issue by akentphonon** [atztogo/phono3py#35]
Dear Prof. Togo,

I am using phonopy2.5.0 and phono3py1.18.3 to compute gruneisen parameter within phono3py.

% phono3py --fc2 --fc3 --dim="4 4 3" --mesh="11 11  11" --gruneisen -c POSCAR

The calculation however fails with the following error:

_Supercells used for fc2 and fc3 have to be same._

This is strange because both 2nd and 3rd order force constants are calculated with same size supercell (4x4x3).

I even tested the development branch, and that also fails with same error.

Any hints/guidance will be helpful..

Best,
Alex

**Comment by atztogo** [comment]
@akentphonon , I confirmed it is broken. I will fix it. Thanks for your report.

**Comment by atztogo** [comment]
I think I could fix it at 8e8eb4d63ce701d0ce7f982b43e3980686d601be. This fix was merged to develop branch.

**Comment by akentphonon** [comment]
It works.


Thanks a lot. I will close this.
