### ISSUE TITLE
Phono3py Installation Problems

### ISSUE THREAD

**Issue by Chengtang-qut** [atztogo/phono3py#37]
Dear Prof. Atztogo,

I installed the latest version of phonopy and phono3py codes through miniconda process. The installed phonopy 2.5 is good for work, however the phono3py shows the following errors when testing by the examples. Since I am a fresh installer, I have no idea about the problems, can I find the solusion here? Thanks in advance.

The error information:
(phono3py) [axd564@login ~]$ phono3py -d --dim="2 2 1" -c POSCAR-unitcell
        _                      _____
  _ __ | |__   ___  _ __   ___|___ / _ __  _   _
 | '_ \| '_ \ / _ \| '_ \ / _ \ |_ \| '_ \| | | |
 | |_) | | | | (_) | | | | (_) |__) | |_) | |_| |
 | .__/|_| |_|\___/|_| |_|\___/____/| .__/ \__, |
 |_|                                |_|    |___/ 
                                          1.18.2

Python version 3.7.6
Spglib version 1.14.1
Traceback (most recent call last):
  File "/home/564/axd564/miniconda/bin/phono3py", line 4, in <module>
    __import__('pkg_resources').run_script('phono3py==1.18.2.post1', 'phono3py')
  File "/home/564/axd564/miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/564/axd564/miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/home/564/axd564/.local/lib/python3.7/site-packages/phono3py-1.18.2.post1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/phono3py", line 389, in <module>
    interface_mode=get_interface_mode(args),
  File "/home/564/axd564/miniconda/lib/python3.7/site-packages/phonopy/interface/calculator.py", line 88, in get_interface_mode
    if mode in args_dict and args_dict[mode]:
TypeError: 'Namespace' object is not subscriptable

btw, I changed the installation path for pip isntall -e ., because I have no access to operate the default folder. Is that the reason for such problem? Phonopy is installed with the same process, it works well.

Best regards

Cheng

**Comment by atztogo** [comment]
Please try the combination of the develop branch of **phonpy** and the develop branch of **phono3py**.

**Comment by Chengtang-qut** [comment]
> Please try the combination of the develop branch of **phonpy** and the develop branch of **phono3py**.

Sorry, Prof. Atztogo, I can not understand it clearly. I simultaneously installed the phonopy and phono3py following the instruction of **"Installation instruction of latest development version of phono3py**" in the website. Are they the develop branches of phonopy and phono3py? but how to combine them together artificially, is there any instructions? Thanks a lot.

**Comment by atztogo** [comment]
If you follow this (https://atztogo.github.io/phono3py/install.html#installation-instruction-of-latest-development-version-of-phono3py) properly, I think it should work. It seems your phono3py is not the same as the develop branch. If you installed by `pip isntall -e .`, then the phono3py script should be in the source code directory. But you call this, `home/564/axd564/.local/lib/python3.7/site-packages/phono3py-1.18.2.post1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/phono3py`. It should be somewhere around `/home/564/axd564/miniconda/bin/phono3py`. If you want to get more helps from other people, please send your question to the phonopy mailing list.

**Comment by atztogo** [comment]
I don't find any problem on the phono3py code (develop branch). So I close this issue.
