### ISSUE TITLE
Can we calculate a band index contributing to intrinsic thermal conductivities at phono3py code?

### ISSUE THREAD

**Issue by Nileme** [atztogo/phono3py#7]
Dear Togo,
    I'm your follower and a graduate. But I have a question puzzling me so long. It is whether we calculate a band index contributing to intrinsic thermal conductivities in phono3py code. Just like at _Lindsay, L.; Broido, D. A.; Reinecke, T. L., First-principles determination of ultrahigh thermal conductivity of boron arsenide: a competitor for diamond? Phys Rev Lett 2013, 111 (2), 025901._ this article Fig. 3, in which the formula is ref[36] k(v)=1/V.... Excause me, I did not write it out in here. Please read the article Fig. 3 and ref[36](just a formula). How can do it in detail? If it do not, can you give me some adives to solve the problem? Thank you so much! Look forward to your reply! Best wishes!
Your Follower: Nileme

**Comment by atztogo** [comment]
This should be discussed in the phonopy mailing list.

C_\lambda, \tau_\lambda, v_\lambda \otimes v_\lambda are in kappa-xxx.hdf5. So you can get the same results by selecting phonons with your band indices, but the integration with delta function has to be done by yourself.

**Comment by atztogo** [comment]
I close this issue.

**Comment by Nileme** [comment]
Thank you so much!
